// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIT7vm6EQwA9t6YQmXnCz06oSo-69lbw4',
    appId: '1:351352890219:web:130bc6e087b75d3dd4622e',
    messagingSenderId: '351352890219',
    projectId: 'fir-series-81300',
    authDomain: 'fir-series-81300.firebaseapp.com',
    storageBucket: 'fir-series-81300.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB94pHcOQi_8o_2Gm83Zj5A4NzHTZd-UFo',
    appId: '1:351352890219:android:870d00866faad963d4622e',
    messagingSenderId: '351352890219',
    projectId: 'fir-series-81300',
    storageBucket: 'fir-series-81300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCunQ3Kdi86bEfo7Kmk5O5UI0WA0a-S26A',
    appId: '1:351352890219:ios:23e2167630093a14d4622e',
    messagingSenderId: '351352890219',
    projectId: 'fir-series-81300',
    storageBucket: 'fir-series-81300.appspot.com',
    iosBundleId: 'com.example.toDoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCunQ3Kdi86bEfo7Kmk5O5UI0WA0a-S26A',
    appId: '1:351352890219:ios:23e2167630093a14d4622e',
    messagingSenderId: '351352890219',
    projectId: 'fir-series-81300',
    storageBucket: 'fir-series-81300.appspot.com',
    iosBundleId: 'com.example.toDoApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIT7vm6EQwA9t6YQmXnCz06oSo-69lbw4',
    appId: '1:351352890219:web:4ee00caaecfb8f3ad4622e',
    messagingSenderId: '351352890219',
    projectId: 'fir-series-81300',
    authDomain: 'fir-series-81300.firebaseapp.com',
    storageBucket: 'fir-series-81300.appspot.com',
  );
}
